USE Traces

IF (OBJECT_ID('TESTE_COLLATION_TABELA_1') IS NOT NULL)
	DROP TABLE TESTE_COLLATION_TABELA_1

CREATE TABLE TESTE_COLLATION_TABELA_1 (
	ID INT IDENTITY(1,1),
	NOME VARCHAR(100),
	ENDERECO VARCHAR(500)
)

IF (OBJECT_ID('TESTE_COLLATION_TABELA_2') IS NOT NULL)
	DROP TABLE TESTE_COLLATION_TABELA_2

CREATE TABLE TESTE_COLLATION_TABELA_2 (
	ID INT IDENTITY(1,1),
	NOME VARCHAR(100),
	ENDERECO VARCHAR(500)
)

GO

INSERT INTO TESTE_COLLATION_TABELA_1
SELECT 'NOME FULANO', REPLICATE('A',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_1
SELECT 'NOME FULANO', REPLICATE('B',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_1
SELECT 'NOME FULANO', REPLICATE('C',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_1
SELECT 'NOME FULANO', REPLICATE('D',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_2
SELECT 'NOME FULANO', REPLICATE('A',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_2
SELECT 'NOME FULANO', REPLICATE('B',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_2
SELECT 'NOME FULANO', REPLICATE('C',500)
GO 50000

INSERT INTO TESTE_COLLATION_TABELA_2
SELECT 'NOME FULANO', REPLICATE('D',500)
GO 50000

CREATE NONCLUSTERED INDEX SK01_TESTE_COLLATION_TABELA_1
ON TESTE_COLLATION_TABELA_1(ENDERECO)
INCLUDE(NOME)
WITH(DATA_COMPRESSION = PAGE)

CREATE NONCLUSTERED INDEX SK01_TESTE_COLLATION_TABELA_2
ON TESTE_COLLATION_TABELA_2(ENDERECO)
INCLUDE(NOME)
WITH(DATA_COMPRESSION = PAGE)


SET STATISTICS IO, TIME ON

-- COM COLLATE
SELECT TOP 1000000 TB1.NOME, TB1.ENDERECO
FROM TESTE_COLLATION_TABELA_1 AS TB1
JOIN TESTE_COLLATION_TABELA_2 AS TB2 ON TB1.ENDERECO = TB2.ENDERECO COLLATE SQL_Latin1_General_CP1_CI_AS

/*
Table 'Worktable'. Scan count 7, logical reads 4758390
Table 'TESTE_COLLATION_TABELA_2'. Scan count 8, logical reads 2614
Table 'TESTE_COLLATION_TABELA_1'. Scan count 9, logical reads 59

SQL Server Execution Times:
   CPU time = 15187 ms,  elapsed time = 15184 ms.
*/

-- SEM COLLATE
SELECT TOP 1000000 TB1.NOME, TB1.ENDERECO
FROM TESTE_COLLATION_TABELA_1 AS TB1
JOIN TESTE_COLLATION_TABELA_2 AS TB2 ON TB1.ENDERECO = TB2.ENDERECO

/*
Table 'TESTE_COLLATION_TABELA_2'. Scan count 20, logical reads 1951
Table 'TESTE_COLLATION_TABELA_1'. Scan count 1, logical reads 4

SQL Server Execution Times:
   CPU time = 1484 ms,  elapsed time = 12345 ms.
*/